"""Private native Genesis boundary."""

def build_contract(manifest_source: str, powers_json: str) -> str: ...
def validate_json(schema_json: str, value_json: str) -> None: ...
def validate_manifest(source: str) -> None: ...
def validate_source_tree(entries_json: str) -> None: ...
def validate_source_icon(contents: bytes) -> None: ...
